# Generated by Django 6.0.4 on 2026-06-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasteBin', '0003_alter_userstext_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstext',
            name='id',
        ),
        migrations.AddField(
            model_name='userstext',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
