# Generated by Django 6.0.6 on 2026-06-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PasteBin', '0004_remove_userstext_id_userstext_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
