# Generated by Django 6.0.4 on 2026-05-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasteBinClone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testNume', models.CharField(max_length=20)),
                ('testText', models.TextField()),
            ],
        ),
    ]
