# Generated by Django 6.0.4 on 2026-06-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasteBinClone', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstext',
            name='userName',
            field=models.CharField(max_length=20),
        ),
    ]
